Introducing Excel look and feel and column specified table filtering
eugener/oxbow pull request #76
Opened 2023-04-06 01:05 UTC by Haripriya-Daggubati

Updated table filtering in such a way that the user feels the Excel type filtering.

In previous scenarios of table filtering, we needed to right-click on the column header to view the search pop-up window. Now we added an icon in the column header for filtering options, and by just clicking on the icon, it shows the search pop-up window.

![Excel_filtering](https://user-images.githubusercontent.com/65753986/230241970-bda40c8e-57c2-4e69-8a85-dcd11a15e88f.png)

And introducing specific column searching along with table searching (search option available for all columns in the table).

![Specific_column_option](https://user-images.githubusercontent.com/65753986/230242162-36591fcf-42b2-443e-a3d5-3fdaf4628cf2.png)

To differentiate filtered columns as part of Excel filtering, introduced two different icons for before and after filtering and also provided the privilege to the user to change the icons as per their needs.

![Before_and_after_filtering_icon](https://user-images.githubusercontent.com/65753986/230243236-a7162292-4cb1-4388-b7b4-11306891a57b.png)

Not as a disadvantage, to more like excel feel removed clear table option in search pop-up window.

2023-04-06 01:38 UTC, eugener requested changes

2023-04-06 01:38 UTC, eugener commented on maven/repository/org/oxbow/swing-bits/1.0.0-SNAPSHOT/maven-metadata-local.xml
> +  <groupId>org.oxbow.se</groupId>
Group and artifact name should not change

2023-04-06 01:38 UTC, eugener commented on maven/repository/org/oxbow/swing-bits/1.0.0-SNAPSHOT/swing-bits-1.0.0-SNAPSHOT.pom
> +	<groupId>org.oxbow.se</groupId>
Group and artifact name should not change

2023-04-06 01:38 UTC, eugener commented on maven/repository/org/oxbow/swing-bits/1.0.0-SNAPSHOT/swing-bits-1.0.0-SNAPSHOT.pom
> -			<url>https://github.com/eugener/oxbow/raw/master/maven/repository</url>
Please keep the ref to the original repo

2023-04-06 01:38 UTC, eugener commented on maven/repository/org/oxbow/swing-bits/maven-metadata-local.xml
> +  <groupId>org.oxbow.se</groupId>
group and artifact name should not change

2023-04-06 01:38 UTC, eugener commented on swingbits/src/main/java/org/oxbow/swingbits/table/filter/TableFilterColumnPopup.java
> +            //removed clear filter for JTable
In my opinion, we should not just remove it, but have API to enable/disable it with default being disabled

2023-04-06 01:38 UTC, eugener commented on swingbits/src/main/java/org/oxbow/swingbits/table/filter/TableRowFilterSupport.java
> +            case DEFAULT:
This is nice - users should be able to choose the renderer

2023-04-06 01:40 UTC, eugener commented
Thank you for a very nice PR!
I had few comments... Once all the issues are resolved, your code can be integrated.

2023-04-07 12:00 UTC, eugener approved these changes
Thank you very much!

2023-04-07 12:01 UTC, merged

2023-04-11 12:48 UTC, Haripriya-Daggubati commented
Thank you for accepting changes to merge.

I have a request to do from your side. Can we deploy the latest changes to maven repository. So, everyone directly use the jar.

2023-04-11 21:52 UTC, eugener commented
I will try to make it happened within the next week.

2023-04-16 20:53 UTC, eugener commented
@Haripriya-Daggubati  

The `v1.3.0` release is available on Maven Central  now 
https://oss.sonatype.org/service/local/repositories/releases/content/org/oxbow/swingbits/

Please let me know if you have any issues.

2023-04-17 13:55 UTC, Haripriya-Daggubati commented
Thank you so much!

I have no issues.